name: health_mate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  flutter_localization: ^0.3.2
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.5.0
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
